CREATE PROCEDURE [dbo].[ExecutionAccessResolve] @UserId UNIQUEIDENTIFIER,@TenantId UNIQUEIDENTIFIER,@BusinessId UNIQUEIDENTIFIER=NULL AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @IdentityTenantId UNIQUEIDENTIFIER=(SELECT TenantId FROM dbo.AppUsers WHERE UserId=@UserId AND IsActive=1);
 DECLARE @CanReadAll bit=CASE WHEN EXISTS(SELECT 1 FROM dbo.AppUsers u JOIN dbo.Tenants identityTenant ON identityTenant.TenantId=u.TenantId AND identityTenant.TenantKey=N'@auraly' JOIN dbo.UserRoles ur ON ur.UserId=u.UserId JOIN dbo.AppRoles r ON r.RoleId=ur.RoleId AND r.IsActive=1 JOIN dbo.RolePermissions rp ON rp.RoleId=r.RoleId JOIN dbo.Permissions p ON p.PermissionId=rp.PermissionId WHERE u.UserId=@UserId AND p.Resource=N'tenants.read') THEN 1 ELSE 0 END;
 IF NOT EXISTS(SELECT 1 FROM dbo.AppUsers WHERE UserId=@UserId AND IsActive=1) OR NOT EXISTS(SELECT 1 FROM dbo.Tenants WHERE TenantId=@TenantId AND IsActive=1) OR(@BusinessId IS NOT NULL AND NOT EXISTS(SELECT 1 FROM dbo.Businesses WHERE BusinessId=@BusinessId AND TenantId=@TenantId AND IsActive=1)) OR(@CanReadAll=0 AND NOT EXISTS(SELECT 1 FROM dbo.UserRoles ur JOIN dbo.AppRoles r ON r.RoleId=ur.RoleId AND r.IsActive=1 LEFT JOIN dbo.Businesses b ON b.BusinessId=ur.BusinessId WHERE ur.UserId=@UserId AND(r.TenantId=@TenantId OR b.TenantId=@TenantId) AND(@BusinessId IS NULL OR ur.BusinessId IS NULL OR ur.BusinessId=@BusinessId))) RETURN;
 ;WITH ApplicableRoles AS(SELECT DISTINCT r.RoleId,r.Name FROM dbo.UserRoles ur JOIN dbo.AppRoles r ON r.RoleId=ur.RoleId AND r.IsActive=1 WHERE ur.UserId=@UserId AND((r.TenantId=@TenantId AND(@BusinessId IS NULL OR ur.BusinessId IS NULL OR ur.BusinessId=@BusinessId)) OR r.TenantId IS NULL OR(@CanReadAll=1 AND r.TenantId=@IdentityTenantId)))
 SELECT N'Role',Name FROM ApplicableRoles UNION ALL SELECT N'Permission',p.Resource FROM ApplicableRoles ar JOIN dbo.RolePermissions rp ON rp.RoleId=ar.RoleId JOIN dbo.Permissions p ON p.PermissionId=rp.PermissionId GROUP BY p.Resource ORDER BY 1,2;
END
