namespace Auraly.Platform.Application.Identity;

public static class PermissionCatalog
{
    public static readonly (string Module, string Action, string Resource, string Description)[] All =
    {
        ("Users", "Read", "users.read", "Ver listado de usuarios"),
        ("Users", "Create", "users.create", "Crear nuevos usuarios"),
        ("Users", "Update", "users.update", "Actualizar usuarios"),
        ("Users", "Delete", "users.delete", "Desactivar usuarios"),
        ("Users", "AssignRole", "users.assign_role", "Asignar roles a usuarios"),
        ("Users", "RemoveRole", "users.remove_role", "Remover roles de usuarios"),
        ("Roles", "Read", "roles.read", "Ver roles"),
        ("Roles", "Create", "roles.create", "Crear roles"),
        ("Roles", "Update", "roles.update", "Actualizar roles"),
        ("Roles", "Delete", "roles.delete", "Desactivar roles"),
        ("Roles", "AssignPermissions", "roles.assign_permissions", "Asignar permisos a roles"),
        ("Permissions", "Read", "permissions.read", "Ver permisos del sistema"),
        ("Tenants", "Read", "tenants.read", "Ver empresas"),
        ("Tenants", "Create", "tenants.create", "Crear empresas"),
        ("Tenants", "WaiveProvisioningPayment", "tenants.provisioning.payment.waive", "Omitir el pago inicial al aprovisionar una empresa"),
        ("Tenants", "Update", "tenants.update", "Actualizar empresas"),
        ("Tenants", "UpdateCapacity", "tenants.capacity.update", "Modificar cupos de usuarios y cajas"),
        ("Tenants", "UpdateStatus", "tenants.status.update", "Activar o inactivar empresas"),
        ("Tenants", "ReadDevices", "tenants.devices.read", "Consultar cajas enroladas de otras empresas"),
        ("Tenants", "RevokeDevices", "tenants.devices.revoke", "Desenrolar cajas de otras empresas"),
        ("Tenants", "ManageBillingPolicy", "tenants.billing.policy.manage", "Configurar la política global de cobranza"),
        ("Tenants", "ConfirmManualBillingPayment", "tenants.billing.payment.confirm_manual", "Confirmar recaudos externos de suscripciones"),
        ("Platform", "AssignPermissions", "platform.permissions.assign", "Delegar permisos de plataforma"),
        ("Platform", "ReadFiscalCertificateExpiry", "platform.fiscal_certificates.expiry.read", "Ver alertas de vencimiento de certificados DIAN"),
        ("Businesses", "Read", "businesses.read", "Ver negocios"),
        ("Businesses", "Create", "businesses.create", "Crear negocios"),
        ("Businesses", "Update", "businesses.update", "Actualizar negocios"),
        ("Businesses", "Delete", "businesses.delete", "Eliminar negocios"),
        ("Services", "Read", "services.read", "Ver servicios"),
        ("Services", "Create", "services.create", "Crear servicios"),
        ("Services", "Update", "services.update", "Actualizar servicios"),
        ("Services", "Delete", "services.delete", "Eliminar servicios"),
        ("ServiceInvoices", "Read", "service-invoices.read", "Consultar facturas y servicios facturables"),
        ("ServiceInvoices", "Create", "service-invoices.create", "Crear facturas de servicios"),
        ("ServiceInvoices", "OverridePrice", "service-invoices.price.override", "Modificar el precio de un servicio al facturar"),
        ("ServiceInvoices", "Discount", "service-invoices.discount", "Aplicar descuentos a servicios"),
        ("ServiceInvoices", "Issue", "service-invoices.issue", "Emitir facturas electrónicas de servicios"),
        ("ServiceInvoices", "Print", "service-invoices.print", "Imprimir facturas de servicios"),
        ("Products", "Read", "products.read", "Ver productos"),
        ("Products", "Update", "products.update", "Activar o inactivar productos"),
        ("Promotions", "Read", "promotions.read", "Ver promociones"),
        ("Promotions", "Create", "promotions.create", "Crear promociones"),
        ("Promotions", "Update", "promotions.update", "Actualizar promociones"),
        ("Promotions", "Delete", "promotions.delete", "Desactivar promociones"),
        ("Employees", "Read", "employees.read", "Ver empleados"),
        ("Employees", "Create", "employees.create", "Crear empleados"),
        ("Employees", "Update", "employees.update", "Actualizar empleados"),
        ("Employees", "Delete", "employees.delete", "Eliminar empleados"),
        ("Reservations", "Read", "reservations.read", "Ver reservas"),
        ("Reservations", "Create", "reservations.create", "Crear reservas"),
        ("Reservations", "Update", "reservations.update", "Actualizar reservas"),
        ("Reservations", "Cancel", "reservations.cancel", "Cancelar reservas"),
        ("Reservations", "Export", "reservations.export", "Exportar reservas"),
        ("Leads", "Read", "leads.read", "Ver leads"),
        ("Leads", "Create", "leads.create", "Crear leads"),
        ("Leads", "Update", "leads.update", "Actualizar leads"),
        ("Leads", "Export", "leads.export", "Exportar leads"),
        ("Campaigns", "Read", "campaigns.read", "Ver campa�as"),
        ("Campaigns", "Create", "campaigns.create", "Crear campa�as"),
        ("Campaigns", "Send", "campaigns.send", "Enviar campa�as"),
        ("Campaigns", "Cancel", "campaigns.cancel", "Cancelar campa�as"),
        ("Conversations", "Read", "conversations.read", "Ver conversaciones"),
        ("Agents", "Read", "agents.read", "Ver agentes IA y contactos de atención"),
        ("Agents", "Update", "agents.update", "Configurar agentes IA y contactos de atención"),
        ("Orders", "Read", "orders.read", "Ver pedidos"),
        ("Payments", "Read", "payments.read", "Ver transacciones de pago"),
        ("Payments", "ConfirmManual", "payments.confirm_manual", "Confirmar pagos manualmente"),
        ("Subscription", "Manage", "subscription.manage", "Consultar y modificar la renovación de la suscripción"),
        ("BusinessConfig", "Read", "business_config.read", "Ver configuración"),
        ("BusinessConfig", "Update", "business_config.update", "Actualizar configuración"),
        ("AuditLogs", "Read", "audit_logs.read", "Ver logs de auditoría"),
        ("Dashboard", "Read", "dashboard.read", "Ver dashboard"),
    };
}

